title: Opendoc - Getting started
remote_theme: opengovsg/opendoc-theme
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
section_order:
  - Getting Started
  - Chapter 2
elastic_search:
  index: intro_index
  doctype: bare
environment: DEV
google_analytics: UA-113717369-6
server_LOCAL: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo-full.png

