title: Opendoc Documentation
remote_theme: opengovsg/opendoc-theme
section_order:
  - Introduction
  - Getting Started
elastic_search:
  index: intro_index
  doctype: bare
environment: DEV
google_analytics: UA-113717369-6
server_LOCAL: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
styling_options:
  primary_brand_color: '#003c98'
  opendoc_logo_path: /assets/images/logo-full.png
  logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5b6a6673d7059a000ff7f7c7
