title: Opendoc - Getting started
remote_theme: opengovsg/opendoc-theme
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
section_order:
  - Getting Started
  - Chapter 2
elastic_search:
  index: templateindex
  doctype: bare
environment: DEV
google_analytics: UA-113717369-6
server_LOCAL: http://127.0.0.1:3000
server_DEV: https://opendoc.sg
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo.png

