title: Opendoc Documentation
remote_theme: opengovsg/opendoc-theme
section_order:
  - Introduction
  - Getting Started
elastic_search:
  index: intro_index
  doctype: bare
environment: DEV
google_analytics: UA-113717369-6
server_LOCAL: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5bbdc1959d1bb0000f818d8c

