title: Opendoc Guide
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-guide
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
offline: false
google_analytics: UA-113717369-7

styling_options:
  primary_brand_color: '#003c98'
  opendoc_logo_path: /assets/logo-full.png
  logo_path: /assets/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5bbdc1959d1bb0000f818d8c

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'Opendoc Guide'
    subtitle: ''
    order:
      - 'getting-started.md'
      - 'import-files.md'
      - 'contribute.md'