title: Opendoc Documentation
remote_theme: opendocsg/opendoc-theme
section_order:
  - Introduction
  - Getting started
  # - Import your files
google_analytics: UA-113717369-7
server_PROD: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
styling_options:
  primary_brand_color: '#003c98'
  opendoc_logo_path: /assets/images/logo-full.png
  logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5bbdc1959d1bb0000f818d8c
